Auto select Credit card type based on number
Mindable/unbounce-scripts pull request #84
Opened 2021-09-01 22:16 UTC by arunnethues

Asana Card
https://app.asana.com/0/676656131310897/1200794831818869/f

2021-09-02 15:38 UTC, gaurav-bains requested changes

2021-09-02 15:38 UTC, gaurav-bains commented on checkout/components/user-payment.js
> +        card_type_drop_down.value ="master";
```suggestion
      if (visa.test(cc)) {
        this.paymentDetails.cardType ="visa";
      } else if (mastercard.test(cc) || mastercard2.test(cc)) {
        this.paymentDetails.cardType ="master";
```
@arunnethues VueJS works on data reactivity, in the version you created, only value of dropdown was changed but the data was not being updated
test using this code on local, and check response in console, first console log will have `this.paymentDetails.cardType` as "" but second console log will show the correct value, I have suggested the code above that updates the data but input selection happens as VueJS being reactive changes the dropdown selection. Does it make sense? If not, I can explain in detail as well
```changeCardType (event) {
      let visa = new RegExp('^4[0-9]{12}(?:[0-9]{3})?$');
      let mastercard = new RegExp('^5[1-5][0-9]{14}$');
      let mastercard2 = new RegExp('^2[2-7][0-9]{14}$');
      let cc = event.target.value;
      let card_type_drop_down= document.getElementById('card_type_drop_down');
      if (visa.test(cc)) {
        card_type_drop_down.value ="visa";
      } else if (mastercard.test(cc) || mastercard2.test(cc)) {
        card_type_drop_down.value ="master";
      }
      console.log(this.paymentDetails);
      this.paymentDetails.cardType = card_type_drop_down.value;
      console.log(this.paymentDetails);
    }
```

2021-09-02 15:52 UTC, gaurav-bains commented on checkout/components/user-payment.js
> +    <select v-model.trim="paymentDetails.cardType" id="card_type_drop_down">
```suggestion
    <select v-model.trim="paymentDetails.cardType">
```

2021-09-02 15:52 UTC, gaurav-bains commented on checkout/components/user-payment.js
> +    <input type="text" maxlength="16" v-model.trim="paymentDetails.cardNumber" @change="changeCardType($event)">
```suggestion
    <input type="text" maxlength="16" v-model.trim="paymentDetails.cardNumber" @change="changeCardType()">
```

2021-09-02 15:53 UTC, gaurav-bains commented on checkout/components/user-payment.js
> +      let cc = event.target.value;
```suggestion
      let cc = paymentDetails.cardNumber;
```

2021-09-02 15:53 UTC, gaurav-bains commented on checkout/components/user-payment.js
> +    changeCardType (event) {
```suggestion
    changeCardType () {
```

2021-09-02 16:34 UTC, pjdarch commented on checkout/components/user-payment.js
> +      let mastercard = new RegExp('^5[1-5][0-9]{14}$');
You can simplify/consolidate the Mastercard into a single regular expression. This reduces the need of running two checks

`'^(5[1-5]|2[2-7])[0-9]{14}$`

2021-09-02 19:23 UTC, arunnethues commented
@gaurav-bains , @pjdarch 
thanks for suggestion, code is updated, please review

2021-09-03 19:02 UTC, pjdarch commented on checkout/components/user-payment.js
> +        this.paymentDetails.cardType ="master";
I know there isn't any linting enforced on the project, but the style has been to single quotes.

```suggestion
        this.paymentDetails.cardType = 'visa';
      } else if (mastercard.test(cc)) {
        this.paymentDetails.cardType = 'master';
```

2021-09-03 19:06 UTC, pjdarch commented
This is just me being partly OCD, as it isn't part of the original PR.. Can you also update L#45? `MasterCard` should be `Mastercard`

`cardTypes: {master: 'MasterCard', visa: 'VISA'}`

2021-09-07 21:12 UTC, arunnethues commented
@pjdarch above changes has been done

2021-09-08 03:25 UTC, pjdarch approved these changes

2021-09-08 16:11 UTC, gaurav-bains approved these changes
eyeballed, looks good

2021-09-08 16:35 UTC, merged